av={util:{fixConsole:function(a){"undefined"===typeof console&&(console={});"undefined"===typeof console.log&&(console.log=a?function(a){alert(a)}:function(){});"undefined"===typeof console.dir&&(console.dir=a?function(a){alert("DIR: "+a)}:function(){})}}};
av.features={ver:"1.17",touch:!1,useragent:"undetected",mobile:"",msPointer:!1,appCache:!1,localStorage:!1,css3anim:!1,css3transform:!1,css3transition:!1,css3transform3d:!1,transformStyle:!1,backfaceVisibility:!1,mode3d:!1,audio:!1,width:window.innerWidth,height:window.innerHeight,detect:function(){if("ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch)this.touch=!0;this.useragent=window.navigator.userAgent;this.mobile=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/BlackBerry/i)||
navigator.userAgent.match(/iPhone|iPad|iPod/i)||navigator.userAgent.match(/IEMobile/i);this.mobile?this.mobile:!1;this.msPointer=window.navigator.msPointerEnabled;this.appCache=!!window.applicationCache;this.localStorage=!!window.localStorage;this.css3anim=this.detectCss("animation");this.css3transform=this.detectCss("transform");this.css3transform3d=this.detectCss("perspective");this.css3transition=this.detectCss("transition");this.transformStyle=this.detectCss("transformStyle");this.mode3d=(this.backfaceVisibility=
this.detectCss("backfaceVisibility"))&&this.transformStyle&&this.css3transform3d&&!av.features.useragent.match(/android 2/ig)&&!av.features.useragent.match(/msie 10/ig);this.audio=!!document.createElement("audio").canPlayType},detectCss:function(a){var d=document.createElement("div"),b=["khtml","ms","O","Moz","Webkit"],c=b.length;if(a in d.style)return!0;for(a=a.charAt(0).toUpperCase()+a.slice(1);c--;)if(b[c]+a in d.style)return b[c];return!1}};
av.touch={state:"none",touchX:-1,touchY:-1,currX:-1,currY:-1,len:-1,dX:0,dY:0,eventTriggered:!1,touched:!1,evStart:0,evMove:0,evEnd:0};av.cards=[];av.cardNames="Bull Butterfly Crab Crocodile Deer Fish Frog Moose Rabbit Rooster Shark Snake Ant Bat Bear Bee Bird Bulldog Cat Chicken Cow Dog Dondey Duck".split(" ");
av.swapCards=function(a,d){var b=$(".card-container,.simple-card").filter("[idx="+a+"]:not('.hide')"),c=$(".card-container,.simple-card").filter("[idx="+d+"]:not('.hide')");if(b.hasClass("animate")||c.hasClass("animate"))return!1;av.features.mode3d?(b.hasClass("flipped")?reverseA=-1:reverseA=1,c.hasClass("flipped")?reverseB=-1:reverseB=1):reverseB=reverseA=1;c.before(b.clone().addClass("hide"));b.before(c.clone().addClass("hide"));b.addClass("selected");c.addClass("selected");if(av.features.css3transition&&
av.features.css3transform){b.css("z-index",11);c.css("z-index",11);var e=b.offset().left-c.offset().left,f=c.offset().top-b.offset().top;"none"==b.css("transform")?cssA="":cssA=b.css("transform");"none"==c.css("transform")?cssB="":cssB=c.css("transform");b.css("transform",cssA+" translate("+reverseA*-e+"px,"+f+"px)");c.css("transform",cssB+" translate("+reverseB*e+"px,"+-f+"px)");b.one("webkitTransitionEnd otransitionend oTransitionEnd MSTransitionEnd msTransitionEnd transitionend",function(){b.remove();
c.remove();$(".card-container.hide,.simple-card.hide").removeClass("hide")})}setTimeout(function(){b.size()&&b.remove();c.size()&&c.remove();$(".card-container.hide,.simple-card.hide").removeClass("hide")},600)};av.randomSwap=function(){var a=Math.round(23*Math.random());do cardB=Math.round(23*Math.random());while(a==cardB);av.swapCards(a,cardB)};
av.rndCards=function(){for(i=1;60>=i;i++){rnd=Math.round(23*Math.random());do rnd2=Math.round(23*Math.random());while(rnd==rnd2);var a=$.extend(!0,{},av.cards[rnd]),d=$.extend(!0,{},av.cards[rnd2]);av.cards[rnd]=d;av.cards[rnd2]=a}};
av.score={isGameEnd:!1,moves:0,score:0,gameTime:0,highScore:0,newHighScore:!1,calculate:function(){this.gameTime=av.gameTimer.counter;this.moves?this.moves:1;this.score=Math.floor(1E8/this.moves/this.gameTime);this.score>this.highScore?(this.highScore=this.score,this.newHighScore=!0,this.save()):this.newHighScore=!1},render:function(){$(".score-table").html(av.tmpl.scoreTemplate(this))},reset:function(){this.moves=0},save:function(){av.features.localStorage&&window.localStorage.setItem("kraken",this.highScore.toString())}};
av.gameTimer={timer:null,counter:0,hold:!0,swapTimer:0,count:function(){this.hold||(this.counter++,this.swapTimer++);var a=Math.floor(this.counter/240);$(".timer span").text(a+" m "+Math.floor((this.counter-240*a)/4)+" s ");$(".moves span").text(av.score.moves);20<this.swapTimer&&(this.swapTimer=0,av.randomSwap())},reset:function(){this.counter=0}};av.sounds={slide:null};
av.endGame=function(){av.score.isGameEnd&&av.score.calculate();av.gameTimer.hold=!0;$(".card-container,.simple-card").addClass("delayed-opacity animated-opacity").css("opacity",0);setTimeout(function(){$(".cards").hide();av.score.render();$(".score-wrapper").addClass("show-score")},1300)};av.tmpl={};
$(window).load(function(){av.util.fixConsole(!1);console.log("ready");window.applicationCache&&window.applicationCache.addEventListener("updateready",function(){window.applicationCache.status==window.applicationCache.UPDATEREADY&&(window.applicationCache.swapCache(),alert("A new version of this site is available."),window.location.reload())},!1);av.features.detect();if(!(av.features.css3transition&&av.features.css3transform||av.features.mobile&&av.features.css3transform))return console.log("browser not supported"),
$("#loading-text").hide(),$("#browser-not-supported").show(),!1;av.features.mode3d||$(".simple-browser").show();av.features.appCache&&$(".feature-offline").show();window.scrollTo(0,1);if(av.features.audio&&!av.features.mobile){av.sounds.slide=new Audio;av.sounds.slide.src="audio/slide.mp3";if("O"==av.features.css3transform||"Moz"==av.features.css3transform)av.sounds.slide.src="audio/slide.ogg";av.sounds.slide.play()}if(av.features.localStorage){var a=parseInt(window.localStorage.getItem("kraken"));
a?(av.score.highScore=a,console.log("high score loaded")):(window.localStorage.setItem("kraken","0"),console.log("setting up localstore"))}$("#container").show();$(".cards").hide();av.tmpl.scoreTemplate=Handlebars.compile($("#temp-score").html());av.tmpl.featuresTemplate=Handlebars.compile($("#temp-featurecheck").html());$(".side-panel").html(av.tmpl.featuresTemplate(av.features));set=[];for(i=1;24>=i;i++)set[i]=!0;for(i=1;12>=i;i++){do rnd=Math.round(24*Math.random());while(!set[rnd]);set[rnd]=!1;
av.cards[i-1]={id:i-1,zodiac:rnd};av.cards[12+i-1]={id:12+i-1,zodiac:rnd}}av.tmpl.cardsTemplate=av.features.mode3d?Handlebars.compile($("#temp-card").html()):Handlebars.compile($("#temp-card-simple").html());setTimeout(function(){$(".left-side").removeClass("open-left");$(".right-side").removeClass("open-right")},0);setTimeout(function(){$(".start-wrapper").css("opacity",0);$("#loader-wrapper").hide();$("#main").show();av.score.render();$(".start-wrapper").show();setTimeout(function(){$(".start-wrapper").css("opacity",
1)},0)},800);av.gameTimer.timer=window.setInterval(function(){av.gameTimer.count()},250);av.features.touch?(a=document.getElementById("container"),a.addEventListener("touchstart",function(a){av.touch.target=a.targetTouches[0].target;av.touch.touchX=a.targetTouches[0].pageX;av.touch.touchY=a.targetTouches[0].pageY;av.touch.state="start";av.touch.evStart++;av.touch.currX=null;av.touch.currY=null;av.touch.len=a.targetTouches.length;av.touch.eventTriggered=!1},!1),a.addEventListener("touchmove",function(a){av.touch.evMove++;
av.touch.state="move";av.touch.currX=a.targetTouches[0].pageX;av.touch.currY=a.targetTouches[0].pageY;av.touch.len=a.targetTouches.length;av.touch.target=a.targetTouches[0].target;dX=av.touch.currX-av.touch.touchX;dY=av.touch.currY-av.touch.touchY;av.touch.dX=dX;av.touch.dY=dY;if(30<(0>dX?-dX:dX)&&10>(0>dY?-dY:dY))0>dX?av.touch.eventTriggered||$(av.touch.target).trigger("swipeleft"):av.touch.eventTriggered||$(av.touch.target).trigger("swiperight"),av.touch.eventTriggered=!0},!1),a.addEventListener("touchend",
function(){av.touch.evEnd++;av.touch.state="end";$(av.touch.target).trigger("tapEvent")},!1),a.addEventListener("MSPointerUp",function(a){$(a.target).trigger("tapEvent")},!1),a="tapEvent"):a="click";$(".cards").on(a,".card-container,.simple-card",function(){if($(this).hasClass("solved")||$(this).hasClass("selected"))return!1;$(this).toggleClass("flipped").addClass("animate");$(this).hasClass("flipped")||av.score.moves++;var a=$(this);setTimeout(function(){a.removeClass("animate")},600);var b=$(".card-container,.simple-card").not(".flipped,.solved").size();
if(2==b){var c=[];$(".card-container,.simple-card").not(".flipped,.solved").each(function(a,b){c[a]=$(b).attr("zod")});c[0]==c[1]&&($(".card-container,.simple-card").filter("[zod='"+c[0]+"']").addClass("solved"),$("#card-name").text(av.cardNames[c[0]-1]),$("#card-name").removeClass("card-name-opacity-animation"),$(".card-name-wrapper").css("top",a.offset().top-20+"px"),setTimeout(function(){$("#card-name").addClass("card-name-opacity-animation")},0))}2<b&&$(".card-container,.simple-card").not(".solved,.animate").addClass("flipped");
0==$(".card-container,.simple-card").not(".solved").size()&&setTimeout(function(){av.score.isGameEnd=!0;av.endGame()},2E3)});$(".button-info").on(a,function(){$(".side-panel").removeClass("hidden-panel-left").toggleClass("hidden-panel");av.gameTimer.hold=$(".side-panel").hasClass("hidden-panel")?!1:!0});$(".side-panel").on(a,function(){$(".side-panel").addClass("hidden-panel");av.gameTimer.hold=!1});$(".start-button").on(a,function(){$(".start-wrapper").css("opacity",0);av.score.reset();av.rndCards();
$(".cards").html(av.tmpl.cardsTemplate(av.cards));$(".card-container,.simple-card").css("opacity",0);$(".cards").show();setTimeout(function(){$(".left-side").addClass("open-left");$(".right-side").addClass("open-right");av.features.audio&&!av.features.mobile&&setTimeout(function(){av.sounds.slide.play();console.log("start sound")},0);av.gameTimer.hold=!0;av.gameTimer.reset()},350);setTimeout(function(){$(".front-wrapper").hide();$(".start-wrapper").hide();$(".card-container,.simple-card").addClass("delayed-opacity animated-opacity").css("opacity",
1);window.scrollTo(0,1)},1100);setTimeout(function(){$(".card-container,.simple-card").removeClass("delayed-opacity animated-opacity").addClass("flipped");av.gameTimer.hold=!1;$("#card-name").text("Find the pairs!");$("#card-name").removeClass("card-name-opacity-animation");$(".card-name-wrapper").css("top","50px");setTimeout(function(){$("#card-name").addClass("card-name-opacity-animation")},0)},2800)});$(".card-container,.simple-card").on("webkitTransitionEnd otransitionend oTransitionEnd MSTransitionEnd msTransitionEnd transitionend",
function(a){$(a.target).removeClass("animate")});$(".button-restart").on(a,function(){av.score.isGameEnd=!1;av.endGame()});$(".score-wrapper").on(a,function(){$(".score-wrapper").removeClass("show-score");setTimeout(function(){$(".front-wrapper").show();setTimeout(function(){$(".left-side").removeClass("open-left");$(".right-side").removeClass("open-right")},0);av.features.audio&&!av.features.mobile&&av.sounds.slide.play();window.scrollTo(0,1)},500);setTimeout(function(){$(".start-wrapper").show();
setTimeout(function(){$(".start-wrapper").css("opacity",1)},0)},1200)})});
